# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches-ignore:
      - 'main'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Upload deploy script
      uses: actions/upload-artifact@v4
      with:
        name: deploy-script
        path: scripts/deploy.sh

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    env:
      AWS_INSTANCE_SG_ID: ${{ secrets.AWS_SECURITY_GROUP_ID }}  
    steps:
      - name: Download deploy script
        uses: actions/download-artifact@v4
        with:
          name: deploy-script
          path: ~/deploy
      - name: configure_aws_credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: us-east-2
      - name: get runner ip address
        id: ip
        uses: haythem/public-ip@v1.3
      - name: whitelist runner ip address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}
      - name: SSH into EC2 and Clone Repo
        run: |    
              scp -o StrictHostKeyChecking=no -P $SSH_PORT /home/runner/deploy/deploy.sh $SSH_USER@$SSH_HOST:/home/ec2-user/
        env:
          SSH_USER: 'ec2-user'
          SSH_HOST: ${{ secrets.AWS_SECRET_ADDRESS }}
          SSH_PORT: '22'
      - name: SSH into EC2 and execute deploy script
        uses: appleboy/ssh-action@master
        env:
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          FROM_EMAIL_PASSWORD: ${{ secrets.FROM_EMAIL_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
        with:
            host: ${{ secrets.AWS_SECRET_ADDRESS }}
            username: ec2-user
            port: 22
            key: ${{ secrets.AWS_SSH_KEY }}
            envs: FROM_EMAIL, FROM_EMAIL_PASSWORD, DB_URL, SUPABASE_API_KEY
            script: |
              chmod +x ~/deploy.sh
              nohup ~/deploy.sh "$SUPABASE_API_KEY" "$DB_URL" "$FROM_EMAIL" "$FROM_EMAIL_PASSWORD" > deploy.log 2>&1 &
              disown
      - name: revoke runner ip address
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32